import { expect,test } from '@playwright/test';
const levelOneSolution=[2,5,14,16,23];
async function seedLevel(page:import('@playwright/test').Page,level=0){await page.addInitScript(index=>{localStorage.setItem('cat-territory-progress-migrated-v3','1');localStorage.setItem('cat-territory-current-level-v3',String(index));},level)}
test.describe('CAT TERRITORY production flows',()=>{
test('core controls and wrong-cat feedback',async({page})=>{await seedLevel(page);await page.goto('/');await expect(page.getByText(/Level 1 ·/)).toBeVisible();await expect(page.getByRole('img',{name:'0 of 3 mistakes'})).toBeVisible();await page.locator('[data-cell-index="0"]').click({button:'right'});await expect(page.locator('[data-cell-index="0"]')).toHaveClass(/mistake-cell/);await expect(page.getByText(/Mistake 1\/3/)).toBeVisible();await expect(page.locator('[data-cell-index="0"] .cat-face')).toHaveCount(0,{timeout:1500})});
test('smart marks animate and undo as one action',async({page})=>{await seedLevel(page);await page.goto('/');const before=await page.locator('.mark-x').count();const first=page.locator('[data-cell-index="0"]'),cat=page.locator('[data-cell-index="5"]');await first.focus();await page.keyboard.press('ArrowDown');await expect(cat).toBeFocused();await page.keyboard.press('c');await expect(cat.locator('.cat-face')).toHaveCount(1);await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await expect(cat).toBeFocused();await expect.poll(()=>page.locator('.mark-x-drawn').count()).toBeGreaterThan(0);await page.getByRole('button',{name:'Undo'}).click();await expect(cat.locator('.cat-face')).toHaveCount(0);await expect(page.locator('.mark-x')).toHaveCount(before)});
test('win dialog has one stable Next level action',async({page})=>{await seedLevel(page);await page.goto('/');for(const index of levelOneSolution.slice(1))await page.locator(`[data-cell-index="${index}"]`).click({button:'right'});const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Perfect.');await expect(dialog.getByRole('button',{name:/Next level/})).toHaveCount(1);await expect(dialog).not.toContainText(/Next territory expands|Start \d+×\d+|Special territory/);await dialog.getByRole('button',{name:/Next level/}).click();await expect(page.getByText(/Level 2 ·/)).toBeVisible()});
test('adjacent territories never share the same computed color',async({page})=>{await seedLevel(page);await page.goto('/');const cells=page.locator('[data-cell-index]');const count=await cells.count();const size=Math.round(Math.sqrt(count));for(let i=0;i<count;i++){const color=await cells.nth(i).evaluate(el=>getComputedStyle(el).backgroundColor);if(i%size<size-1)expect(await cells.nth(i+1).evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(color);if(i+size<count)expect(await cells.nth(i+size).evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(color)}});
test('rules and progress remain usable',async({page})=>{await seedLevel(page);await page.goto('/');await page.getByRole('button',{name:'How to play'}).click();const rules=page.getByRole('dialog',{name:'Give every cat its own territory.'});await expect(rules).toBeVisible();await rules.getByRole('button',{name:'More rules'}).click();await expect(rules.getByText(/Smart marks:/)).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:/Progress and achievements/i}).click();await expect(page.getByLabel('Territory Journal')).toBeVisible()});
test('Daily is fullscreen and protects restart',async({page})=>{await seedLevel(page);await page.goto('/');await page.getByRole('button',{name:'Open Daily Territory'}).click();const daily=page.getByRole('dialog',{name:"Today's territory"});await expect(daily).toBeVisible();await expect(page.getByRole('button',{name:'Back to endless'})).toBeFocused();const first=daily.locator('[data-cell-index="0"]');await first.click();await daily.getByRole('button',{name:'Restart'}).click();await expect(daily.getByRole('button',{name:'Restart?'})).toBeVisible();await expect(first.locator('.mark-x')).toHaveCount(1);await page.keyboard.press('Escape');await expect(daily).toHaveCount(0)});
});
