/* Generated by the build: a complete, immutable release, including lazy chunks. */
const CACHE = "cat-territory-release-__RELEASE_VERSION__";
const FILES = /* __PRECACHE__ */ [];
const scope = self.registration.scope;
const shell = new URL("./index.html", scope).href;
const assets = new Set(FILES.map((path) => new URL(path, scope).href));

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      try {
        const cache = await caches.open(CACHE);
        await cache.addAll(
          FILES.map(
            (path) => new Request(new URL(path, scope), { cache: "reload" }),
          ),
        );
      } catch (error) {
        await caches.delete(CACHE);
        throw error;
      }
    })(),
  );
  // A new release waits for old tabs to close. Never replace their lazy chunks mid-game.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith("cat-territory-") && key !== CACHE)
          .map((key) => caches.delete(key)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (
    request.method !== "GET" ||
    new URL(request.url).origin !== self.location.origin
  )
    return;
  const navigation = request.mode === "navigate";
  if (!navigation && !assets.has(request.url)) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      // HTML and its modules always come from the same installed release.
      const cached = await cache.match(navigation ? shell : request.url);
      return cached ?? fetch(request);
    })(),
  );
});
